before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt532
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo apt-get update
  - sudo dpkg -r cmake cmake-data
  - sudo apt-get -y install cmake
  - sudo apt-get -y install pep8 pyflakes
  - sudo apt-get -y install qt53quickcontrols qt53graphicaleffects
  - sudo apt-get -y install qt53tools qt53declarative

before_script:
  - wget http://download.kde.org/stable/frameworks/5.11/extra-cmake-modules-5.11.0.tar.xz
  - tar -xvf extra-cmake-modules-5.11.0.tar.xz
  - cd extra-cmake-modules-5.11.0 && cmake -DCMAKE_INSTALL_PREFIX=/usr . && make && sudo make install
  - source /opt/qt53/bin/qt53-env.sh
  - git clone git://github.com/papyros/qml-extras.git
  - git clone git://github.com/papyros/qml-material.git
  - pushd qml-extras
  - qmake
  - sudo make install
  - popd
  - pushd qml-material
  - qmake
  - sudo make install
  - popd

script:
  - source /opt/qt53/bin/qt53-env.sh
  - cmake .
  - make test

notifications:
  slack: papyros:gI5qeLsvC7CWBzwiZvpbN4Z5
